manifest:
  version: 0.9
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
    - name: jtguggedal
      url-base: https://github.com/jtguggedal
  projects:
    - name: sdk-nrf
      path: nrf
      repo-path: fw-nrfconnect-nrf
      remote: jtguggedal
      revision: aws-fota-handle-duplicate
      import: true
  self:
    path: firmware
